# Generated by Django 3.1.1 on 2020-09-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_boy_girl_love'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together={('b', 'g')},
        ),
    ]
