# Generated by Django 3.1.1 on 2020-09-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200919_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Love',
        ),
    ]
