# Generated by Django 3.1.1 on 2020-09-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(to='app01.Girl'),
        ),
    ]
