# Generated by Django 3.1.1 on 2020-09-20 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_boy_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boy',
            name='m',
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.boy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.girl')),
            ],
            options={
                'unique_together': {('b', 'g')},
            },
        ),
    ]
