# Generated by Django 3.1.1 on 2020-09-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200920_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(through='app01.Love', to='app01.Girl'),
        ),
    ]
