# Generated by Django 3.1.2 on 2020-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201013_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=2, verbose_name='性别'),
        ),
    ]
