# Generated by Django 3.1.1 on 2020-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='f',
            field=models.FileField(default=11, upload_to=''),
        ),
    ]
