# Generated by Django 3.1.1 on 2020-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='color',
            field=models.IntegerField(default=1, verbose_name=[(1, '黑色'), (2, '白色'), (3, '蓝色')]),
        ),
    ]
