# Generated by Django 3.1.1 on 2020-09-21 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('passwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.CharField(error_messages={'c1': '优先错误'}, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='c1', message='错误了', regex='root_\\d+')]),
        ),
    ]
