# Generated by Django 3.1.1 on 2020-09-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
            ],
        ),
        migrations.CreateModel(
            name='UToU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boy', to='app01.userinfo')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girl', to='app01.userinfo')),
            ],
        ),
    ]
