# Generated by Django 3.1.1 on 2020-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_utou'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='m',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
