# Generated by Django 3.1.1 on 2020-10-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('date2', models.DateTimeField(auto_now=True)),
                ('penname', models.CharField(default='', max_length=255)),
                ('hot_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('date2', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_pro', to='app01.professional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
