# Generated by Django 3.1.2 on 2020-10-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='url别名'),
        ),
    ]
