# Generated by Django 3.1.2 on 2020-10-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20201008_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=32, verbose_name='一级菜单图标'),
        ),
    ]
