# Generated by Django 3.1.1 on 2020-09-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UToU',
        ),
    ]
