# Generated by Django 3.1.2 on 2020-10-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20201007_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于一个非菜单的权限需要选择一个可以成为菜单的权限，用户做默认展开', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='rbac.permission', verbose_name='关联的权限'),
        ),
    ]
