# Generated by Django 3.1.2 on 2020-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='url别名'),
        ),
    ]
