# Generated by Django 3.1.2 on 2020-10-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='一级菜单')),
                ('icon', models.CharField(max_length=32, verbose_name='一级菜单图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的URL')),
                ('name', models.CharField(blank=True, max_length=16, unique=True, verbose_name='url别名')),
                ('menu', models.ForeignKey(blank=True, help_text='null表示不是菜单，非null表示是二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.menu', verbose_name='所属一级菜单')),
                ('pid', models.ForeignKey(blank=True, help_text='对于一个非菜单的权限需要选择一个可以成为菜单的权限，用户做默认展开', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='app01.permission', verbose_name='关联的权限')),
            ],
        ),
    ]
